language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
